name: Pull Request on SemVer tag
on: 
  push:
    tags:
        - 'v?[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
        - 'v?[0-9]+.[0-9]+.[0-9]'

jobs:
  auto-pull-request:
    strategy:
      matrix:
        env:
          - prod
          - preprod
          - test
          - dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v7
        name: Create Pull Request
        with:
          commit-message: "Bump version to ${{ github.ref }}"
          title: "${{ matrix.env }} - bump version to ${{ github.ref }}"
          body: |
            This PR was created automatically in response to a new SemVer tag. The version has been bumped to ${{ github.ref }}.

            This PR is done for the `${{ matrix.env }}` environment.
          branch: "bump-version-${{ github.ref }}"
          base: main
