name: Pull Request on SemVer tag
on: 
  push:
    tags:
        - 'v?[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
        - 'v?[0-9]+.[0-9]+.[0-9]'

jobs:
  auto-pull-request:
    strategy:
      matrix:
        env:
          - prod
          - preprod
          - test
          - dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v7
        name: Create Pull Request
        with:
          commit-message: "Bump version to ${{ github.ref }}"
          title: "${{ matrix.env }} - bump version to ${{ github.ref }}"
          body: |
            This PR was created automatically in response to a new SemVer tag. The version has been bumped to ${{ github.ref }}.

            This PR is done for the `${{ matrix.env }}` environment.
          branch: "bump-version-${{ github.ref }}"
          base: main
  enable-auto-delete:
    needs: auto-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate required time for B
        id: calc-time
        run: |
          # Calculate the required time (e.g., 5 minutes from now)
          NEXT_RUN_TIME=$(date -u -d "+5 minutes" +"%M %H * * *")
          echo "next_run_time=$NEXT_RUN_TIME" >> $GITHUB_ENV

      - name: Update clear-semver-pr.yml cron schedule
        run: |
          # Use yq to update the cron value in B.yml
          yq eval ".on.schedule[0].cron = env(next_run_time)" -i .github/workflows/clear-semver-pr.yml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/workflows/clear-semver-pr.yml
          git commit -m "Update clear-semver-pr.yml cron schedule"
          git push

      - name: Enable B workflow
        run: gh workflow enable clear-semver-pr.yml
